# action.yml
name: 'diffctx'
description: 'A GitHub action for automatically evaluating the function level impacts of Pull Requests.'
branding:
  color: 'green'
  icon: 'at-sign'
inputs:
  lang:
    description: 'language of your repo'
    required: true
    default: 'python'
  before_sha:
    description: 'before sha'
    required: true
    default: ${{ github.event.pull_request.base.sha }}
  after_sha:
    description: 'after sha'
    required: true
    default: ${{ github.sha }}
  repo_token:
    description: "A GitHub token for API access. Defaults to {{ github.token }}."
    default: "${{ github.token }}"
    required: false
  issue_number:
    description: "issue number"
    default: "${{ github.event.number }}"
    required: false
  debug_mode:
    description: "enable debug mode if not empty"
    default: ""
    required: false
  lsif_file:
    description: "specific lsif file input"
    default: ""
    required: false
  index_cmd:
    description: "custom index command"
    default: ""
    required: false
runs:
  using: 'docker'
  image: 'williamfzc/diffctx:v0.3.11'
  args:
    - ${{ inputs.lang }}
    - ${{ inputs.before_sha }}
    - ${{ inputs.after_sha }}
    - ${{ inputs.repo_token }}
    - ${{ inputs.issue_number }}
    - ${{ inputs.debug_mode }}
    - ${{ inputs.lsif_file }}
    - ${{ inputs.index_cmd }}
