on:
  push:
    tags:
      - 'v*'

permissions:
  pull-requests: write

jobs:
  release_test:
    runs-on: ubuntu-latest
    name: Release Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test Action
        uses: ./
        with:
          lang: "python"
          debug_mode: "true"
